### ISSUE TITLE
cant make in debian

### ISSUE THREAD

**Issue by alnc** [gamelinux/passivedns#62] opened 2015-11-03 16:26 UTC
make
Making all in src
make[1]: Entering directory `/root/passivedns/src'
gcc -O3  -c passivedns.c -o passivedns.o
gcc -O3  -c dns.c -o dns.o
dns.c: In function 'cache_dns_objects':
dns.c:361: error: 'LDNS_RR_TYPE_NSEC3PARAM' undeclared (first use in this function)
dns.c:361: error: (Each undeclared identifier is reported only once
dns.c:361: error: for each function it appears in.)
dns.c: In function 'print_passet':
dns.c:748: error: 'LDNS_RR_TYPE_NSEC3PARAM' undeclared (first use in this function)
make[1]: *** [dns.o] Error 1
make[1]: Leaving directory `/root/passivedns/src'
make: *** [all-recursive] Error 1

any idea?

tkx

**Comment by muratbeser** [comment] 2015-11-04 02:05
I just able to make it on Debian Jessie  can u provide more information about your system.
Also I'm trying to debianize passivedns .

**Comment by thus** [comment] 2015-11-04 08:25
@alnc: Which version of LDNS are you using? It looks like LDNS_RR_TYPE_NSEC3PARAM was added to LDNS in 2012, so it's a real possibility that an older version is causing this problem.

**Comment by thus** [comment] 2015-11-05 08:47
I was able to reproduce this error on an old test machine running Debian Squeeze (oldoldstable).

Could you try the latest git version? I pushed a patch that (hopefully) should fix this issue.

**Comment by thus** [comment] 2015-12-25 10:42
No reply from reporter, so closing issue.

**Closed by thus** 2015-12-25 10:42 UTC
